apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: streamlit-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8501
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              value: "testdb"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: NodePort

